# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This page documents a basic array list class 
email: marcus.flores09gmail.com 
description: > # this means to ignore newlines until "baseurl:"
       In order to practice working with Git and Jekyll, I have deployed this site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcf08.github.io/" # the base hostname & protocol for your site
github_username: marcf08 

# Build settings
markdown: kramdown
